### ISSUE TITLE
Style.css and script.js

### ISSUE THREAD

**Issue by b-cheung** [THS-CompSci/WebApp#6]
we need to combine the 2 style sheets to one and have only one main style.css and script.js.
@THS-CompSci/hall-pass-web-app

**Comment by PoldervaartS** [comment]
some pages will need different scripts to start on load, so we cant have just 1 central JS

**Comment by NuttKatyISD** [comment]
Typically a website will have a CSS file that has classes for multiple pages. It's only loaded once on the first page load and then cached for the rest. If nothing else, it makes it way easier to maintain.

I think this came up though since there was a Style.css and style.css committed to the repo. 

For JavaScript, you can abstract the code out into functions instead of doing everything inline. Then, on pageA you call the function for that page, same thing with pageB, etc.

**Comment by b-cheung** [comment]
@PoldervaartS i understand what ur saying but u can still have multiple functions for the javascript file and just access whichever function you need for that page. having one js and one css file makes it more organized and easier to edit them because they r all in one file.
